version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tksoporte-backend
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=192.168.40.129
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tksoporte-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped